// <auto-generated />
using System;
using FlourishWellness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlourishWellness.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325170143_AddSurveyLockAuditLog")]
    partial class AddSurveyLockAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlourishWellness.Models.Community", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<int>("CommunityKey")
                        .HasColumnType("int");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAMAccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "CommunityKey");

                    b.ToTable("Community", (string)null);
                });

            modelBuilder.Entity("FlourishWellness.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyYearId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyYear");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("SurveyYearId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FlourishWellness.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommunityKey")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("SAMAccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyYearId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyYear");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SurveyYearId");

                    b.HasIndex("UserId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("FlourishWellness.Models.ResponseAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int");

                    b.Property<string>("SAMAccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResponseAuditLogs");
                });

            modelBuilder.Entity("FlourishWellness.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyYearId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyYear");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("SurveyYearId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("FlourishWellness.Models.SurveyLockAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorRole")
                        .HasColumnType("int");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CommunityKey")
                        .HasColumnType("int");

                    b.Property<bool>("NewLockState")
                        .HasColumnType("bit");

                    b.Property<int>("SurveyYearId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SurveyLockAuditLogs");
                });

            modelBuilder.Entity("FlourishWellness.Models.SurveyYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("SurveyYear", (string)null);
                });

            modelBuilder.Entity("FlourishWellness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SAMAccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FlourishWellness.Models.UserSurveyStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommunityKey")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("SurveyYearId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyYear");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyYearId");

                    b.HasIndex("UserId", "SurveyYearId", "CommunityKey")
                        .IsUnique()
                        .HasFilter("[CommunityKey] IS NOT NULL");

                    b.ToTable("UserSurveyStatuses");
                });

            modelBuilder.Entity("FlourishWellness.Models.Community", b =>
                {
                    b.HasOne("FlourishWellness.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlourishWellness.Models.Question", b =>
                {
                    b.HasOne("FlourishWellness.Models.Section", "Section")
                        .WithMany("Questions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlourishWellness.Models.SurveyYear", "SurveyYear")
                        .WithMany()
                        .HasForeignKey("SurveyYearId")
                        .HasPrincipalKey("Year")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("SurveyYear");
                });

            modelBuilder.Entity("FlourishWellness.Models.Response", b =>
                {
                    b.HasOne("FlourishWellness.Models.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlourishWellness.Models.SurveyYear", "SurveyYear")
                        .WithMany()
                        .HasForeignKey("SurveyYearId")
                        .HasPrincipalKey("Year")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlourishWellness.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SurveyYear");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlourishWellness.Models.Section", b =>
                {
                    b.HasOne("FlourishWellness.Models.Section", "ParentSection")
                        .WithMany("Subsections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlourishWellness.Models.SurveyYear", "SurveyYear")
                        .WithMany("Sections")
                        .HasForeignKey("SurveyYearId")
                        .HasPrincipalKey("Year")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSection");

                    b.Navigation("SurveyYear");
                });

            modelBuilder.Entity("FlourishWellness.Models.UserSurveyStatus", b =>
                {
                    b.HasOne("FlourishWellness.Models.SurveyYear", "SurveyYear")
                        .WithMany()
                        .HasForeignKey("SurveyYearId")
                        .HasPrincipalKey("Year")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlourishWellness.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyYear");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlourishWellness.Models.Question", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FlourishWellness.Models.Section", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Subsections");
                });

            modelBuilder.Entity("FlourishWellness.Models.SurveyYear", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
